name: CI Gradle

on:
  push:
  pull_request:

permissions:
  contents: read
  checks: write 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      #  Donner les droits
      - name: Make gradlew executable
        run: chmod +x gradlew

      # Build (sans tests)
      - name: Build project
        run: ./gradlew build -x test

      #  Lancer les tests
      - name: Run tests
        run: ./gradlew test

      #  Publier les résultats de tests
      - name: Publish Test Results
        uses: dorny/test-reporter@v1
        if: always()   # important même si les tests échouent
        with:
          name: Tests Results
          path: build/test-results/test/*.xml
          reporter: java-junit
